---
title: "featureReductionPCA"
output: html_document
---

This Markdown aims at doing feature reduction using PCA (princomp).

```{r libraries, include=FALSE}
library(dplyr)
```

## Data

The input contains only the high median correlation compounds.
The input data is a 3752 by 803 matrix.
There are 3752 different observations and 799 features (extracted with CellProfiler).
Each compound (938 different) has 4 replicates.

```{r import data}
set.seed(42)
pf <- readRDS("../input/Pf_Gustafsdottir.rds")
dim(pf$data)

# Remove the negative control from the data
pf$data <- filter(pf$data, !Image_Metadata_BROAD_ID %in% "")
dim(pf$data)
```

## Feature Selection

```{r pca}
feat <- pf$data[, pf$feat_cols]

res.pca <- prcomp(feat, scale = FALSE)

names(res.pca)
head(res.pca$sdev)
head(unclass(res.pca$rotation)[, 1:4])


# Eigenvalues
eig <- (res.pca$sdev)^2
# Variances in percentage
variance <- eig*100/sum(eig)
# Cumulative variances
cumvar <- cumsum(variance)
eig.feat <- data.frame(eig = eig, variance = variance,
                     cumvariance = cumvar)
head(eig.feat, n = 30L)

summary(res.pca)

barplot(eig.feat[, 2], names.arg=1:nrow(eig.feat), 
       main = "Variances",
       xlab = "Principal Components",
       ylab = "Percentage of variances",
       col ="steelblue",
       xlim = range(0, 30))
# Add connected line segments to the plot
lines(x = 1:nrow(eig.feat), 
      eig.feat[, 2], 
      type="b", pch=19, col = "red")

```

```{r}
# correlation between variables and principal components

# Helper function : 
# Correlation between variables and principal components
var_cor_func <- function(var.loadings, comp.sdev){
  var.loadings*comp.sdev
  }
# Variable correlation/coordinates
loadings <- res.pca$rotation
sdev <- res.pca$sdev
var.coord <- var.cor <- t(apply(loadings, 1, var_cor_func, sdev))
head(var.coord[, 1:4])

#Cos2 : quality of representation for variables on the factor map
#The cos2 of variables are calculated as the squared coordinates : var.cos2 = var.coord * var.coord

var.cos2 <- var.coord^2
head(var.cos2[, 1:4])

ind.coord <- res.pca$x
head(ind.coord[, 1:4])

plot(ind.coord[,1], ind.coord[,2], pch = 19,  
     xlab="PC1 - 35.31%",ylab="PC2 - 24.3%")
abline(h=0, v=0, lty = 2)
text(ind.coord[,1], ind.coord[,2], labels=rownames(ind.coord),
        cex=0.7, pos = 3)

```

