---
title: "sc feature selection findCorrelation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(dplyr)
library(tidyverse)
library(stringr)
```

## import the data

```{r import data, message=FALSE}
# name of the single cell data file
filename.sc <- "neg_ctrl_samples.rds" #"BBBC022_sampled_10000.rds"

# name of the profile data (in order to remove not meaningfull data)
data.filename <- "Pf_Gustafsdottir.rds"

# import data
pf.sc <- readRDS(file.path("..", "..", "input", "BBBC022_2013", "BBBC022_dmso", filename.sc))  #readRDS(file.path("..", "..", "input", "BBBC022_2013", "single_cells", filename.sc)) %>% scale() %>% as.data.frame()
pf <- readRDS(file.path("..", "..", "input", "BBBC022_2013", "old", data.filename))

# difference of features name between old and new version:
# Hoechst -> DNA, Ph_golgi -> AGP, Syto -> RNA
#pf$feat_cols <- str_replace(pf$feat_cols, "Hoechst", "DNA")
#pf$feat_cols <- str_replace(pf$feat_cols, "Ph_golgi", "AGP")
#pf$feat_cols <- str_replace(pf$feat_cols, "Syto", "RNA")
#cl <- colnames(pf$data)
#cl <- str_replace(cl, "Hoechst", "DNA")
#cl <- str_replace(cl, "Ph_golgi", "AGP")
#cl <- str_replace(cl, "Syto", "RNA")
#colnames(pf$data) <- cl

pf.sc <- pf.sc$data
profiles <- pf.sc[ , colSums(is.na(pf.sc)) == 0] # remove features (columns) where there are NA

feat.delete <- setdiff(colnames(profiles), pf$feat_cols) # features that are in profiles but not in pf

profiles <- profiles[, !names(profiles) %in% feat.delete] # remove features

dim(profiles)

variables <-
  colnames(profiles) %>% str_subset("^Cells_|^Cytoplasm_|^Nuclei_")
```

```{r feature seleciton}
start.time <- Sys.time()

# remove features that are too correlated (threshold of .9)
profiles %<>%
  cytominer::select(
    sample = profiles,
    variables = variables,
    operation = "correlation_threshold"
  )
variables <-
  names(profiles) %>% str_subset("^Cells_|^Cytoplasm_|^Nuclei_")

# size: 382 features

end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken 

#10,000 cells 4.767532 secs
#200,000 cells 1.368276 mins

variables.fs.sc.fc <- variables
save(variables.fs.sc.fc, file="../../input/BBBC022_2013/selected_single_cell_zoom/feat_names/selected_features_200000cells_findCorr.Rda")
```


